name: Harvey Tan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.69319
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dadee1'
    - '#79859b'
    - '#010101'
    - '#414141'
    - '#656976'
  brandStrength: 1
  lightness: 0.4360639078076929
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
