name: Harvey Tan
favicon: null
layout_spectrum: 0.9356340870726854
typography_spectrum: 0.7899149442091584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13524720631539822
  lightness: 0.4360639078076929
  saturation: 0.9869476535823196
  rhythmicContrast: 0.44835793995298445
purpose: []
